name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y --no-install-recommends install texlive-latex-extra shellcheck devscripts poppler-utils
    - name: l3build check
      run: l3build check || { cat build/test/*.diff; false; }
    - name: Other tests
      run: tests/run.sh
    - name: Code check
      run: |
        l3build unpack
        shellcheck build/unpacked/pdfjam
        checkbashisms -xp build/unpacked/pdfjam
