name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install texlive-latex-extra shellcheck devscripts
    - name: Build
      run: |
        PATH="$PATH:." l3build check || for i in build/test/*.diff; do echo; echo "$i"; cat "$i"; done
        ./build.sh
        cd built_package/pdfjam*
        unzip tests.zip
        tests/run.sh
        shellcheck bin/pdfjam
        checkbashisms -xp bin/pdfjam
